# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFinalProjectSe():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_finalProjectSe(self):
    self.driver.get("http://localhost/LiadAyalDanielShimon/")
    self.driver.set_window_size(728, 912)
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, "li").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "li").text == "LiadT3"
    self.driver.find_element(By.LINK_TEXT, "BACK").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
    self.driver.find_element(By.NAME, "author").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1)").text == "Tan Ah Teck"
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2)").text == "Mohd Ali"
    self.driver.find_element(By.LINK_TEXT, "BACK").click()
  
